// <auto-generated />
using System;
using CliCommandCreator.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CliCommandCreator.Migrations
{
    [DbContext(typeof(CommandContext))]
    [Migration("20220116190651_MigDbCommands")]
    partial class MigDbCommands
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("CliCommandCreator.Model.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseCommandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Params")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseCommandId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("CliCommandCreator.Model.Command", b =>
                {
                    b.HasOne("CliCommandCreator.Model.Command", "BaseCommand")
                        .WithMany()
                        .HasForeignKey("BaseCommandId");
                });
#pragma warning restore 612, 618
        }
    }
}
